export const strings = {
  app: {
    name: "Party Planner",
    description: "Planificá la build de cada miembro de tu party de AION 2 y el orden para las raids.",
  },
  home: {
    title: "Armá tu party para la raid",
    body: "Cargá a cada amigo en el orden de la party, planificá su equipo y sus habilidades, y compará las builds lado a lado antes de entrar.",
  },
  createParty: {
    heading: "Crear una party",
    nameLabel: "Nombre de la party",
    namePlaceholder: "Raid del jueves",
    passwordLabel: "Contraseña",
    passwordHint: "Mínimo 8 caracteres. Se la pasás a tus amigos junto con el link.",
    creationCodeLabel: "Código de creación",
    creationCodeHint: "Lo tiene quien administra el sitio.",
    submit: "Crear party",
    submitting: "Creando…",
    errors: {
      name: "Ponele un nombre de 1 a 80 caracteres.",
      password: "La contraseña tiene que tener entre 8 y 128 caracteres.",
      creationCode: "El código de creación no es correcto.",
      disabled: "Crear parties está deshabilitado en este sitio.",
      unexpected: "No se pudo crear la party. Probá de nuevo en un rato.",
    },
  },
  links: {
    heading: "Guardá estos links",
    body: "Es la única vez que se muestran. Si los perdés, podés generar links nuevos desde la party.",
    editLabel: "Link de edición",
    editHint: "Para quienes arman las builds.",
    viewLabel: "Link de solo lectura",
    viewHint: "Para quienes solo miran.",
    copy: "Copiar",
    copied: "Copiado",
    open: "Ir a la party",
  },
  unlock: {
    heading: "Entrar a la party",
    body: "Ingresá la contraseña que te pasaron junto con el link.",
    passwordLabel: "Contraseña",
    submit: "Entrar",
    submitting: "Entrando…",
    missingLink: "Este link está incompleto. Pedile a quien armó la party que te lo vuelva a pasar.",
    errors: {
      invalid: "El link o la contraseña no son correctos.",
      locked: "Demasiados intentos. Esperá 15 minutos y probá de nuevo.",
      unexpected: "No se pudo entrar. Probá de nuevo en un rato.",
    },
  },
  party: {
    locked: "Para ver esta party, abrí el link que te pasaron.",
    accessEdit: "Podés editar",
    accessView: "Solo lectura",
  },
  settings: {
    heading: "Acceso",
    rotateTitle: "Generar links nuevos",
    rotateBody: "Los links actuales dejan de funcionar y todos, vos incluido, tienen que volver a entrar con los nuevos.",
    rotateSubmit: "Generar links nuevos",
    passwordTitle: "Cambiar la contraseña",
    passwordBody: "Todos tienen que volver a entrar con la contraseña nueva.",
    passwordLabel: "Contraseña nueva",
    passwordSubmit: "Cambiar contraseña",
    passwordChanged: "Listo. Pasales la contraseña nueva a tus amigos.",
    errors: {
      forbidden: "Necesitás el link de edición para hacer esto.",
      password: "La contraseña tiene que tener entre 8 y 128 caracteres.",
      unexpected: "No se pudo guardar el cambio. Probá de nuevo en un rato.",
    },
  },
  footer: {
    gameData: "Datos del juego: servidores de Taiwán de AION 2 (en inglés)",
    noGlobalApi: "Los servidores Global todavía no tienen API pública",
  },
} as const;
