export const strings = {
  app: {
    name: "Party Planner",
    description: "Planificá la build de cada miembro de tu party de AION 2 y el orden para las raids.",
  },
  home: {
    title: "Armá tu party para la raid",
    body: "Cargá a cada amigo en el orden de la party, planificá su equipo y sus habilidades, y compará las builds lado a lado antes de entrar.",
  },
  createParty: {
    heading: "Crear una party",
    nameLabel: "Nombre de la party",
    namePlaceholder: "Raid del jueves",
    passwordLabel: "Contraseña",
    passwordHint: "Mínimo 8 caracteres. Se la pasás a tus amigos junto con el link.",
    creationCodeLabel: "Código de creación",
    creationCodeHint: "Lo tiene quien administra el sitio.",
    submit: "Crear party",
    submitting: "Creando…",
    errors: {
      name: "Ponele un nombre de 1 a 80 caracteres.",
      password: "La contraseña tiene que tener entre 8 y 128 caracteres.",
      creationCode: "El código de creación no es correcto.",
      disabled: "Crear parties está deshabilitado en este sitio.",
      tooManyAttempts: "Demasiados intentos. Esperá 15 minutos y probá de nuevo.",
      unexpected: "No se pudo crear la party. Probá de nuevo en un rato.",
    },
  },
  links: {
    heading: "Guardá estos links",
    body: "Es la única vez que se muestran. Si los perdés, podés generar links nuevos desde la party.",
    editLabel: "Link de edición",
    editHint: "Para quienes arman las builds.",
    viewLabel: "Link de solo lectura",
    viewHint: "Para quienes solo miran.",
    copy: "Copiar",
    copied: "Copiado",
    open: "Ir a la party",
  },
  unlock: {
    heading: "Entrar a la party",
    body: "Ingresá la contraseña que te pasaron junto con el link.",
    passwordLabel: "Contraseña",
    submit: "Entrar",
    submitting: "Entrando…",
    missingLink: "Este link está incompleto. Pedile a quien armó la party que te lo vuelva a pasar.",
    errors: {
      invalid: "El link o la contraseña no son correctos.",
      locked: "Demasiados intentos. Esperá 15 minutos y probá de nuevo.",
      unexpected: "No se pudo entrar. Probá de nuevo en un rato.",
    },
  },
  party: {
    locked: "Para ver esta party, abrí el link que te pasaron.",
    accessEdit: "Podés editar",
    accessView: "Solo lectura",
    nameLabel: "Party",
    memberCount: (count: number) => (count === 1 ? "1 miembro · en orden de party" : `${count} miembros · en orden de party`),
    noMembersCount: "Sin miembros",
    addMember: "Agregar miembro",
    compositionLabel: "Composición de la party",
    gapsLabel: "Huecos",
    allRolesCovered: "Todos los roles cubiertos",
    missingRole: { Tank: "Sin tank", Healer: "Sin healer", DPS: "Sin DPS", Support: "Sin support" },
    emptyTitle: "Todavía no hay miembros",
    emptyBody: "Agregá a cada amigo en el orden de la raid. Quien tenga el link de edición puede abrir la party y planificar su build.",
    emptyAction: "Agregar el primer miembro",
    reorderHint: "Arrastrá las filas, o enfocá el asa y usá las flechas, para cambiar el orden.",
    rosterLabel: "Orden de la party",
    handleLabel: (name: string, position: number, total: number) =>
      `Reordenar a ${name}, posición ${position} de ${total}. Usá las flechas para moverlo.`,
    moveUp: (name: string) => `Subir a ${name}`,
    moveDown: (name: string) => `Bajar a ${name}`,
    gearLabel: "Equipo",
    gearMissing: (count: number) => (count === 1 ? "1 vacía" : `${count} vacías`),
    gearComplete: "Completo",
    averageEnchantLabel: "Encant. medio",
    skillsLabel: "Habilidades",
    remove: "Quitar",
    confirmRemove: "Confirmar",
    announceMoved: (name: string, position: number, total: number) => `${name} pasó a la posición ${position} de ${total}`,
    announceAdded: (name: string) => `${name} se sumó a la party`,
    announceRemoved: (name: string) => `${name} salió de la party`,
    saving: "Guardando…",
    saved: "Cambios guardados",
    conflict: "Alguien cambió la party al mismo tiempo. Se cargó la versión más nueva.",
    rejected: "No se pudo guardar el cambio. Se cargó la versión más nueva.",
    saveFailed: "No se pudo guardar. Revisá tu conexión y probá de nuevo.",
    full: "La party ya tiene el máximo de miembros.",
    catalogMissing: "Todavía no se cargaron los datos del juego. Las builds guardadas están a salvo.",
    dismiss: "Entendido",
  },
  addMember: {
    nameLabel: "Nombre",
    namePlaceholder: "Nombre del personaje",
    classLabel: "Clase",
    roleLabel: "Rol",
    cancel: "Cancelar",
    submit: "Agregar a la party",
  },
  settings: {
    heading: "Acceso",
    rotateTitle: "Generar links nuevos",
    rotateBody: "Los links actuales dejan de funcionar y todos, vos incluido, tienen que volver a entrar con los nuevos.",
    rotateSubmit: "Generar links nuevos",
    passwordTitle: "Cambiar la contraseña",
    passwordBody: "Todos tienen que volver a entrar con la contraseña nueva.",
    passwordLabel: "Contraseña nueva",
    passwordSubmit: "Cambiar contraseña",
    passwordChanged: "Listo. Pasales la contraseña nueva a tus amigos.",
    errors: {
      forbidden: "Necesitás el link de edición para hacer esto.",
      password: "La contraseña tiene que tener entre 8 y 128 caracteres.",
      unexpected: "No se pudo guardar el cambio. Probá de nuevo en un rato.",
    },
  },
  footer: {
    gameData: "Datos del juego: servidores de Taiwán de AION 2 (en inglés)",
    catalogSize: (items: number, classes: number) => `${items} objetos · ${classes} clases`,
    noGlobalApi: "Los servidores Global todavía no tienen API pública",
  },
} as const;
