export const strings = {
  app: {
    name: "Party Planner",
    description: "Planificá la build de cada miembro de tu party de AION 2 y el orden para las raids.",
  },
  home: {
    title: "Armá tu party para la raid",
    body: "Cargá a cada amigo en el orden de la party, planificá su equipo y sus habilidades, y compará las builds lado a lado antes de entrar.",
  },
  createParty: {
    heading: "Crear una party",
    nameLabel: "Nombre de la party",
    namePlaceholder: "Raid del jueves",
    passwordLabel: "Contraseña",
    passwordHint: "Mínimo 8 caracteres. Se la pasás a tus amigos junto con el link.",
    creationCodeLabel: "Código de creación",
    creationCodeHint: "Lo tiene quien administra el sitio.",
    submit: "Crear party",
    submitting: "Creando…",
    errors: {
      name: "Ponele un nombre de 1 a 80 caracteres.",
      password: "La contraseña tiene que tener entre 8 y 128 caracteres.",
      creationCode: "El código de creación no es correcto.",
      disabled: "Crear parties está deshabilitado en este sitio.",
      tooManyAttempts: "Demasiados intentos. Esperá 15 minutos y probá de nuevo.",
      unexpected: "No se pudo crear la party. Probá de nuevo en un rato.",
    },
  },
  links: {
    heading: "Guardá estos links",
    body: "Es la única vez que se muestran. Si los perdés, podés generar links nuevos desde la party.",
    editLabel: "Link de edición",
    editHint: "Para quienes arman las builds.",
    viewLabel: "Link de solo lectura",
    viewHint: "Para quienes solo miran.",
    copy: "Copiar",
    copied: "Copiado",
    open: "Ir a la party",
  },
  unlock: {
    heading: "Entrar a la party",
    body: "Ingresá la contraseña que te pasaron junto con el link.",
    passwordLabel: "Contraseña",
    submit: "Entrar",
    submitting: "Entrando…",
    missingLink: "Este link está incompleto. Pedile a quien armó la party que te lo vuelva a pasar.",
    errors: {
      invalid: "El link o la contraseña no son correctos.",
      locked: "Demasiados intentos. Esperá 15 minutos y probá de nuevo.",
      unexpected: "No se pudo entrar. Probá de nuevo en un rato.",
    },
  },
  party: {
    locked: "Para ver esta party, abrí el link que te pasaron.",
    accessEdit: "Podés editar",
    accessView: "Solo lectura",
    nameLabel: "Party",
    memberCount: (count: number) => (count === 1 ? "1 miembro · en orden de party" : `${count} miembros · en orden de party`),
    noMembersCount: "Sin miembros",
    addMember: "Agregar miembro",
    compositionLabel: "Composición de la party",
    gapsLabel: "Huecos",
    allRolesCovered: "Todos los roles cubiertos",
    missingRole: { Tank: "Sin tank", Healer: "Sin healer", DPS: "Sin DPS", Support: "Sin support" },
    emptyTitle: "Todavía no hay miembros",
    emptyBody: "Agregá a cada amigo en el orden de la raid. Quien tenga el link de edición puede abrir la party y planificar su build.",
    emptyAction: "Agregar el primer miembro",
    reorderHint: "Arrastrá las filas, o enfocá el asa y usá las flechas, para cambiar el orden.",
    rosterLabel: "Orden de la party",
    handleLabel: (name: string, position: number, total: number) =>
      `Reordenar a ${name}, posición ${position} de ${total}. Usá las flechas para moverlo.`,
    moveUp: (name: string) => `Subir a ${name}`,
    moveDown: (name: string) => `Bajar a ${name}`,
    gearLabel: "Equipo",
    gearMissing: (count: number) => (count === 1 ? "1 vacía" : `${count} vacías`),
    gearComplete: "Completo",
    averageEnchantLabel: "Encant. medio",
    skillsLabel: "Habilidades",
    remove: "Quitar",
    confirmRemove: "Confirmar",
    announceMoved: (name: string, position: number, total: number) => `${name} pasó a la posición ${position} de ${total}`,
    announceAdded: (name: string) => `${name} se sumó a la party`,
    announceRemoved: (name: string) => `${name} salió de la party`,
    saving: "Guardando…",
    saved: "Cambios guardados",
    conflict: "Alguien cambió la party al mismo tiempo. Se cargó la versión más nueva.",
    rejected: "No se pudo guardar el cambio. Se cargó la versión más nueva.",
    saveFailed: "No se pudo guardar. Revisá tu conexión y probá de nuevo.",
    full: "La party ya tiene el máximo de miembros.",
    catalogMissing: "Todavía no se cargaron los datos del juego. Las builds guardadas están a salvo.",
    dismiss: "Entendido",
  },
  build: {
    backToParty: "← Party",
    openBuild: "Abrir build",
    memberNameLabel: "Nombre del miembro",
    classLabel: "Clase",
    roleLabel: "Rol",
    importCharacter: "Importar desde personaje",
    importUnavailable: "Disponible cuando salga la API de Global",
    readinessGear: "Equipo",
    readinessAcquired: "Obtenido",
    readinessEnchant: "Encant. medio",
    readinessSkills: "Habilidades",
    equipmentHeading: "Equipamiento",
    acquiredLegend: (count: number) => `${count} obtenidas`,
    plannedLegend: (count: number) => `${count} planificadas`,
    missingLegend: (count: number) => `${count} vacías`,
    groups: {
      weapons: "Armas",
      armor: "Armadura",
      accessories: "Accesorios",
      arcana: "Arcana",
      runes: "Runas",
      companions: "Alas y mascota",
    },
    emptySlot: "Vacía",
    emptySlotHint: "Elegí un objeto",
    noCatalog: "Sin catálogo todavía",
    noCatalogHint: "No cuenta como hueco",
    unknownItem: "Objeto fuera del catálogo",
    slotAria: (slot: string, state: string) => `${slot}: ${state}`,
    acquired: "obtenido",
    planned: "planificado",
    exceed: (level: number) => `Exceed ${level}`,
    skillsHeading: "Habilidades",
    skillSummary: (planned: number, total: number, equipped: number) =>
      `${planned} de ${total} planificadas · ${equipped} en barra`,
    plannedLevels: "Niveles planificados",
    pointsNeeded: "Puntos necesarios",
    pointCap: "Límite de puntos",
    unknownCost: "Costo desconocido",
    unknownCap: "Desconocido",
    pointsNote:
      "Todavía no se conocen el costo por nivel ni el límite de puntos. Este contador va a mostrar totales reales cuando existan esos datos.",
    skillGroups: { Active: "Active", Passive: "Passive", Dp: "Dp" },
    skillGroupCount: (planned: number, total: number, equipped: number | null) =>
      `${planned}/${total} planificadas${equipped === null ? "" : ` · ${equipped} en barra`}`,
    requiredLevel: (level: number) => `Nv. req. ${level}`,
    notPlanned: "sin planificar",
    levelLabel: (level: number) => `Nv ${level}`,
    lowerSkill: (name: string) => `Bajar ${name}`,
    raiseSkill: (name: string) => `Subir ${name}`,
    onBar: "En barra",
    offBar: "Fuera",
    equipSkill: (name: string) => `Equipar ${name} en la barra de habilidades`,
    alwaysActive: "Siempre activa",
    noSkills: "Todavía no hay habilidades de esta clase en el catálogo.",
  },
  picker: {
    title: (slot: string) => `Elegir ${slot.toLowerCase()}`,
    close: "Cerrar",
    searchPlaceholder: "Buscar objetos por nombre",
    searchLabel: "Buscar objetos",
    allCategories: "Todas",
    categoryLabel: "Categoría",
    gradeLabel: "Grado",
    count: (count: number, limited: boolean) =>
      `${limited ? "Más de " : ""}${count} ${count === 1 ? "objeto" : "objetos"}`,
    loadFailed: "No se pudieron cargar los datos del juego. Tus builds guardadas están a salvo.",
    loadFailedBody: "El catálogo de objetos viene de los servidores de Taiwán. Probá de nuevo en un momento.",
    retry: "Reintentar",
    noResults: (query: string) =>
      query ? `Ningún objeto coincide con “${query}”` : "Ningún objeto coincide con estos filtros",
    noResultsBody: "Probá con un nombre más corto u otro grado.",
    clearFilters: "Borrar búsqueda y filtros",
    equippedTag: "Equipado",
    selectPrompt: "Elegí un objeto para ver sus atributos y ajustar el encantamiento y el exceed.",
    enchant: "Encantamiento",
    lowerEnchant: "Bajar encantamiento",
    raiseEnchant: "Subir encantamiento",
    enchantLevel: "Nivel de encantamiento",
    exceed: "Exceed",
    status: "Estado",
    planned: "Planificado",
    acquired: "Obtenido",
    clearSlot: "Vaciar ranura",
    cancel: "Cancelar",
    equip: "Equipar",
    update: "Actualizar ranura",
    announceEquipped: (item: string, slot: string) => `${item} asignado a ${slot}`,
  },
  slots: {
    MainHand: "Mano principal",
    SubHand: "Mano secundaria",
    Helmet: "Casco",
    Shoulder: "Hombreras",
    Torso: "Torso",
    Pants: "Piernas",
    Gloves: "Guantes",
    Boots: "Botas",
    Cape: "Capa",
    Necklace: "Collar",
    Pendant: "Colgante",
    Amulet: "Amuleto",
    Earring1: "Aro 1",
    Earring2: "Aro 2",
    Ring1: "Anillo 1",
    Ring2: "Anillo 2",
    Bracelet1: "Pulsera 1",
    Bracelet2: "Pulsera 2",
    Belt: "Cinturón",
    Brooch1: "Broche 1",
    Brooch2: "Broche 2",
    Seal1: "Sello 1",
    Seal2: "Sello 2",
    Rune1: "Runa 1",
    Rune2: "Runa 2",
    Wing: "Alas",
    Pet: "Mascota",
  } as Record<string, string>,
  slotLabel: (slotPosName: string) => {
    const arcana = /^Arcana(\d+)$/.exec(slotPosName);
    if (arcana) return `Arcana ${arcana[1]}`;
    return strings.slots[slotPosName] ?? slotPosName;
  },
  screens: {
    label: "Pantallas",
    party: "Party",
    compare: "Comparar",
  },
  compare: {
    heading: "Comparar",
    note: "Las ranuras vacías tienen borde punteado. Un objeto es débil si su grado es menor que Unique o si tiene 5 o más niveles de encantamiento menos que el promedio de la party en esa ranura. Tocá una celda para editarla.",
    gapsOnly: "Solo huecos",
    membersLabel: "Miembros a comparar",
    slotColumn: "Ranura",
    summary: "Resumen",
    gearComplete: "Equipo completo",
    acquired: "Obtenido",
    averageEnchant: "Encant. medio",
    skillsPlanned: "Habilidades planificadas",
    skillsOnBar: "Habilidades en barra",
    empty: "Vacía",
    gaps: (count: number) => (count === 1 ? "1 hueco" : `${count} huecos`),
    belowGrade: "· bajo Unique",
    belowAverage: (levels: number) => `· ${levels} bajo el promedio`,
    noneSelectedTitle: "No hay miembros seleccionados",
    noneSelectedBody: "Activá al menos un miembro arriba.",
    noMembersTitle: "No hay miembros para comparar",
    noMembersBody: "Primero agregá miembros a la party.",
    goToParty: "Ir a la party",
    noGaps: "Sin huecos ni ranuras débiles en los miembros seleccionados.",
  },
  addMember: {
    nameLabel: "Nombre",
    namePlaceholder: "Nombre del personaje",
    classLabel: "Clase",
    roleLabel: "Rol",
    cancel: "Cancelar",
    submit: "Agregar a la party",
  },
  settings: {
    heading: "Acceso",
    rotateTitle: "Generar links nuevos",
    rotateBody: "Los links actuales dejan de funcionar y todos, vos incluido, tienen que volver a entrar con los nuevos.",
    rotateSubmit: "Generar links nuevos",
    passwordTitle: "Cambiar la contraseña",
    passwordBody: "Todos tienen que volver a entrar con la contraseña nueva.",
    passwordLabel: "Contraseña nueva",
    passwordSubmit: "Cambiar contraseña",
    passwordChanged: "Listo. Pasales la contraseña nueva a tus amigos.",
    errors: {
      forbidden: "Necesitás el link de edición para hacer esto.",
      password: "La contraseña tiene que tener entre 8 y 128 caracteres.",
      unexpected: "No se pudo guardar el cambio. Probá de nuevo en un rato.",
    },
  },
  footer: {
    gameData: "Datos del juego: servidores de Taiwán de AION 2 (en inglés)",
    catalogSize: (items: number, classes: number) => `${items} objetos · ${classes} clases`,
    noGlobalApi: "Los servidores Global todavía no tienen API pública",
  },
} as const;
